// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package openapi

import (
	"github.com/uptrace/bun"
	"golden-app/backend/example"
	"golden-app/backend/internal/config"
	"golden-app/backend/internal/presentation/api"
	"golden-app/backend/users"
	"log/slog"
)

// Injectors from wire.go:

// Initialize builds the same Huma API InitializeApp builds — every
// domain registered through the same Register calls — over the config,
// logger and database the caller supplies. `gonext openapi` passes a
// fixed config, a discarding logger and a *bun.DB that never connects;
// registration only constructs repositories that hold the handle, so
// nothing dials. Run `gonext generate` after changing the provider list
// below.
func Initialize(cfg config.Config, logger *slog.Logger, db *bun.DB) (*Spec, error) {
	echo := api.NewEcho(logger)
	sessionIssuer := users.ProvideSessionIssuer(db)
	resolver := users.ProvideResolver(sessionIssuer)
	authConfig := api.ProvideAuthConfig()
	humaAPI := api.NewHumaAPI(echo, resolver, authConfig, logger)
	healthzRegistered := api.ProvideHealthzRegistration(humaAPI, logger)
	readyzRegistered := api.ProvideReadyzRegistration(humaAPI, db, logger)
	registered, err := example.ProvideRegistration(humaAPI, db, logger)
	if err != nil {
		return nil, err
	}
	usersRegistered, err := users.ProvideRegistration(humaAPI, db, cfg, logger, sessionIssuer)
	if err != nil {
		return nil, err
	}
	spec := NewSpec(humaAPI, healthzRegistered, readyzRegistered, registered, usersRegistered)
	return spec, nil
}
