// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"golden-app/backend/example"
	"golden-app/backend/internal/config"
	"golden-app/backend/internal/database"
	"golden-app/backend/internal/logging"
	"golden-app/backend/internal/presentation/api"
	"golden-app/backend/users"
)

// Injectors from wire.go:

// InitializeApp builds the full dependency graph and returns the assembled
// App, a cleanup func that closes the DB pool, and any error hit along the
// way. Run `gonext generate` after editing the provider list below.
func InitializeApp(ctx context.Context) (*App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger := logging.New(configConfig)
	echo := api.NewEcho(logger)
	string2 := configConfig.DatabaseURL
	db, cleanup, err := database.ProvideDB(ctx, string2)
	if err != nil {
		return nil, nil, err
	}
	sessionIssuer := users.ProvideSessionIssuer(db)
	resolver := users.ProvideResolver(sessionIssuer)
	authConfig := api.ProvideAuthConfig()
	humaAPI := api.NewHumaAPI(echo, resolver, authConfig, logger)
	healthzRegistered := api.ProvideHealthzRegistration(humaAPI, logger)
	readyzRegistered := api.ProvideReadyzRegistration(humaAPI, db, logger)
	registered, err := example.ProvideRegistration(humaAPI, db, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	usersRegistered, err := users.ProvideRegistration(humaAPI, db, configConfig, logger, sessionIssuer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewApp(echo, logger, configConfig, healthzRegistered, readyzRegistered, registered, usersRegistered)
	return app, func() {
		cleanup()
	}, nil
}
