// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"golden-app/backend/internal/config"
	"golden-app/backend/internal/database"
	"golden-app/backend/internal/logging"
	"golden-app/backend/internal/presentation/api"
	"golden-app/backend/tracks"
	"golden-app/backend/users"
)

// Injectors from wire.go:

// InitializeApp builds the full dependency graph — config, logger, DB
// pool, HTTP server, and every domain's endpoint registration — and
// returns the assembled App, a cleanup func (closing the DB pool),
// and any error hit along the way. Run `wire ./backend/cmd/server/...`
// (see `make generate`) to regenerate wire_gen.go after changing the
// provider list below.
func InitializeApp(ctx context.Context) (*App, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	logger := logging.New(configConfig)
	echo := api.NewEcho(logger)
	humaAPI := api.NewHumaAPI(echo)
	healthzRegistered := api.ProvideHealthzRegistration(humaAPI)
	string2 := configConfig.DatabaseURL
	db, cleanup, err := database.ProvideDB(ctx, string2)
	if err != nil {
		return nil, nil, err
	}
	readyzRegistered := api.ProvideReadyzRegistration(humaAPI, db)
	registered, err := tracks.ProvideRegistration(humaAPI, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	usersRegistered, err := users.ProvideRegistration(humaAPI, db, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewApp(echo, logger, configConfig, healthzRegistered, readyzRegistered, registered, usersRegistered)
	return app, func() {
		cleanup()
	}, nil
}
